# Generated by Django 5.2.4 on 2025-07-28 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование задачи"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "К выполнению"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнено"),
                            ("canceled", "Отменено"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("deadline", models.DateField(verbose_name="Срок выполнения")),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="employees.employee",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tasks.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
    ]
